=== h4yde/repositorio-codigo/recursos/xml/dtd/codigos.dtd
<!ELEMENT codigos (codigo*)>
	<!ELEMENT usuario (nombre, lenguaje, brush, ncol, nfil, lineas)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT lenguaje (#PCDATA)>
		<!ELEMENT brush (#PCDATA)>
		<!ELEMENT ncol (#PCDATA)>
		<!ELEMENT nfil (#PCDATA)>
		<!ELEMENT lineas (#PCDATA)>

=== h4yde/repositorio-codigo/recursos/xml/codigos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE codigos SYSTEM "dtd/codigos.dtd">
<codigos>
	
	

<codigo><nombre>holaMundo</nombre><lenguaje>c</lenguaje><brush>shBrushCpp</brush><ncol>10</ncol><nfil>10</nfil><lineas>6</lineas></codigo></codigos>
