=== h4yde/repositorio-codigo/recursos/xml/dtd/comentarios.dtd
<!ELEMENT comentarios (coment*)>
	<!ELEMENT coment (nombre, calificacion, desta, texto)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT calificacion (#PCDATA)>
		<!ELEMENT desta (#PCDATA)>
		<!ELEMENT texto (#PCDATA)>

=== h4yde/repositorio-codigo/recursos/xml/comentarios/2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comentarios SYSTEM "../dtd/comentarios.dtd">
<comentarios>
	<coment>
		<nombre>hayde</nombre>
		<calificacion>3</calificacion>
		<desta>si</desta>
		<texto>No se trata de sustos. Parece que te van a matar de a de veras. Y yo ya no quiero volver allá.
        —Anda otra vez. Solamente otra vez, a ver qué consigues.
        —No. No tengo ganas de eso, yo soy tu hijo. Y si voy mucho con ellos, acabarán por saber quién soy y les dará por afusilarme a mí también. Es mejor dejar las cosas de este tamaño.</texto>
	</coment>
	<coment>
		<nombre>hayde2</nombre>
		<calificacion>5</calificacion>
		<desta>si</desta>
		<texto> —¡Diles que no me maten, Justino! Anda, vete a decirles eso. Que por caridad. Así diles. Diles que lo hagan por caridad.
        —No puedo. Hay allí un sargento que no quiere oír hablar nada de ti.
        —Haz que te oiga. Date tus mañas y dile que para sustos ya ha estado bueno. Dile que lo haga por caridad de Dios.</texto>
	</coment>
	<coment>
		<nombre>hayde3</nombre>
		<calificacion>3</calificacion>
		<desta>no</desta>
		<texto>Parece que te van a matar de a de veras. Y yo ya no quiero volver allá. —Anda otra vez. Solamente otra vez, a ver qué consigues. —No. No tengo ganas de eso, yo soy tu hijo. Y si voy mucho con ellos, acabarán por saber quién soy y les dará por afusilarme a mí también. Es mejor dejar las cosas de este tamañ</texto>
	</coment>
	<coment>
		<nombre>alumno1</nombre>
		<calificacion>6</calificacion>
		<desta>no</desta>
		<texto>No se trata de sustos. Parece que te van a matar de a de veras. Y yo ya no quiero volver allá. —Anda otra vez. Solamente otra vez, a ver qué consigues. —No. No tengo ganas de eso, yo soy tu hijo. Y si voy mucho con ellos, acabarán por saber quién soy y les dará por afusilarme a mí también. Es mejor dejar las cosas de este tamaño.
—¡Diles que no me maten, Justino! Anda, vete a decirles eso. Que por caridad. Así diles. Diles que lo hagan por caridad.
		</texto>
	</coment>
	<coment>
		<nombre>alumno3</nombre>
		<calificacion>6</calificacion>
		<desta>no</desta>
		<texto>me maten, Justino! Anda, vete a decirles eso. Que por caridad. Así diles. Diles que lo hagan por caridad. —No puedo. Hay allí un sargento que no quiere oír hablar nada de ti. —Haz que te oiga. Date tus mañas y dile que para sustos ya ha estado bueno. Dile que lo haga por caridad de Dios.
		</texto>
	</coment>
</comentarios>

=== h4yde/repositorio-codigo/recursos/xml/comentarios/holaMundo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comentarios SYSTEM "../dtd/comentarios.dtd">
<comentarios>
<coment><nombre>Victoria</nombre><calificacion>5</calificacion><desta>no</desta><texto>-¡Diles que no me maten, Justino! Anda, vete a decirles eso. Que por caridad. Así diles. Diles que lo hagan por caridad. -No puedo. Hay allí un sargento que no quiere oír hablar nada de ti. -Haz que te oiga. Date tus mañas y dile que para sustos ya ha estado bueno. Dile que lo haga por caridad de Dios.</texto></coment><coment><nombre>Hayde</nombre><calificacion>5</calificacion><desta>si</desta><texto>Prueba el 04/05/2018, parece que todo funciona bien :D</texto></coment></comentarios>
